/** Данные для seed: статьи и игры */
export const SEED_ARTICLES = [
  {
    title: 'Настройка Windows 11 для максимального FPS',
    preview: 'Отключение фоновых служб, настройка питания и игрового режима для лучшей производительности.',
    content: 'Полный гайд по оптимизации Windows 11: отключите лишние службы, включите Game Mode, поставьте режим «Высокая производительность», обновите драйверы GPU. Прирост 10–20% FPS в большинстве игр.',
    category: 'Windows',
    isPremium: false,
  },
  {
    title: 'Сборка игрового ПК за 100 000 ₽',
    preview: 'Оптимальная конфигурация для CS2, PUBG и современных AAA-игр в 2026 году.',
    content: 'Ryzen 5 7600 + RTX 4060 Ti + 32GB DDR5 + NVMe 1TB. CS2 на 300+ FPS, PUBG на высоких 144+ FPS. Не экономьте на БП и RAM.',
    category: 'Сборка ПК',
    isPremium: false,
  },
  {
    title: 'Разгон видеокарты NVIDIA: безопасный гайд',
    preview: 'Как разогнать GPU через MSI Afterburner без риска для железа.',
    content: 'MSI Afterburner: +15–25 MHz Core Clock за шаг, стресс-тест после каждого шага, температуры не выше 83°C. Типичный прирост 5–15% FPS.',
    category: 'Разгон GPU',
    isPremium: true,
  },
  {
    title: 'Лучшие настройки PUBG для конкурентной игры',
    preview: 'Конфиг графики, sens и настройки сети для максимального преимущества.',
    content: 'Anti-Aliasing Very Low, тени Very Low, VSync Off, Motion Blur Off. Проводной интернет, DPI 400–800, отключённое ускорение мыши в Windows.',
    category: 'PUBG',
    isPremium: true,
  },
  {
    title: 'Фикс лагов и фризов в Stalzone',
    preview: 'Решение проблем с производительностью и сетевыми задержками в Stalzone.',
    content: 'Понизьте тени и дальность прорисовки, отключите оверлей Discord, очистите кэш шейдеров, выберите ближайший сервер.',
    category: 'Stalzone',
    isPremium: false,
  },
  {
    title: 'Оптимизация CS2: настройки для 300+ FPS',
    preview: 'Конфиг, autoexec и системные настройки для Counter-Strike 2.',
    content: 'Запуск: -high -novid -nojoy +fps_max 0. autoexec: cl_interp_ratio 1, r_dynamic 0. Все настройки Low/Medium, Fullscreen Optimizations off.',
    category: 'CS2',
    isPremium: true,
  },
  {
    title: 'Valorant: настройки для стабильных 240 FPS',
    preview: 'Графика, сеть и конфиг для соревновательного Valorant.',
    content: 'Все настройки Low, Multithreaded Rendering On, NVIDIA Reflex On+Boost. Закройте фоновые приложения и используйте проводное подключение.',
    category: 'Valorant',
    isPremium: true,
  },
  {
    title: 'Как убрать input lag на мониторе',
    preview: 'Overdrive, G-Sync/FreeSync и правильная частота обновления.',
    content: 'Включите максимальный Hz в Windows, настройте Overdrive на среднем уровне без артефактов, используйте полноэкранный режим без рамки.',
    category: 'Мониторы',
    isPremium: true,
  },
  {
    title: 'Очистка Windows от мусора без риска',
    preview: 'Безопасная оптимизация автозагрузки, служб и временных файлов.',
    content: 'Диспетчер задач → автозагрузка, очистка диска, отключение ненужных служб. Не удаляйте системные компоненты без понимания.',
    category: 'Windows',
    isPremium: false,
  },
  {
    title: 'NVIDIA Reflex и Low Latency Mode',
    preview: 'Как снизить задержку ввода в соревновательных шутерах.',
    content: 'В панели NVIDIA: Low Latency Mode On+Boost. В играх включайте NVIDIA Reflex. Комбинируйте с высоким Hz монитора.',
    category: 'Разгон GPU',
    isPremium: true,
  },
  {
    title: 'Сборка ПК за 150 000 ₽ — топ за свои деньги',
    preview: 'Конфигурация для 2K gaming и стриминга.',
    content: 'Ryzen 7 7800X3D + RTX 4070 Super + 32GB DDR5. Идеально для CS2, PUBG и AAA в 1440p. Качественное охлаждение обязательно.',
    category: 'Сборка ПК',
    isPremium: true,
  },
  {
    title: 'Apex Legends: лучший конфиг FPS',
    preview: 'Настройки графики и launch options для Apex.',
    content: 'Texture Streaming Budget минимум, Model Quality Low, Impact Marks Off. Launch options: -novid -high +fps_max 0.',
    category: 'Apex Legends',
    isPremium: true,
  },
  {
    title: 'Lies of P: оптимизация на среднем ПК',
    preview: 'DLSS, FSR и настройки для стабильных 60+ FPS.',
    content: 'DLSS/FSR Quality, тени Medium, Motion Blur Off. Закройте браузер и Discord overlay при прохождении тяжёлых зон.',
    category: 'Lies of P',
    isPremium: true,
  },
  {
    title: 'Horizon Zero Dawn: настройки для ПК',
    preview: 'FSR 2.0, текстуры и эффекты для баланса качества и FPS.',
    content: 'FSR 2.0 Quality, Ultimate Render Quality Medium, Depth of Field Off. Обновите драйверы — игра чувствительна к версии.',
    category: 'Horizon Zero Dawn',
    isPremium: false,
  },
  {
    title: 'Stalzone: продвинутый конфиг сети',
    preview: 'Снижение пинга и потерь пакетов для Stalzone.',
    content: 'Проводное подключение, DNS 1.1.1.1, отключение VPN, выбор сервера с пингом <50ms. Закройте торренты и стримы на фоне.',
    category: 'Stalzone',
    isPremium: true,
  },
  {
    title: 'Оптимизация SSD и перенос игр',
    preview: 'Куда ставить игры и как ускорить загрузку.',
    content: 'Windows и игры на NVMe, Steam Library на отдельном диске при нехватке места. Оставьте 15% свободного места на системном SSD.',
    category: 'Железо',
    isPremium: false,
  },
  {
    title: 'PUBG: звук и настройки аудио',
    preview: 'Как лучше слышать шаги и выстрелы в PUBG.',
    content: 'Stereo Headphones, HRTF включён, музыка 0%, эффекты 100%. В Windows отключите улучшения звука для гарнитуры.',
    category: 'PUBG',
    isPremium: true,
  },
  {
    title: 'CS2: прицелы про-игроков и настройка',
    preview: 'Коллекция конфигов прицела и чувствительности.',
    content: 'eDPI 800–1200 для большинства про. Яркий контрастный прицел, отключённый blur, raw input 1. Тренируйте aim на community maps.',
    category: 'CS2',
    isPremium: true,
  },
];

export const SEED_GAMES = [
  {
    title: 'Counter-Strike 2',
    imageUrl: '/images/games/counter-strike-2-1783714992916.jpg',
    optimizationTip: 'Запуск: -high -novid -nojoy. Все тени Low, Multisampling 2x. fps_max 0 в консоли. NVIDIA Reflex On.',
  },
  {
    title: 'PUBG: Battlegrounds',
    imageUrl: '/images/games/pubg-battlegrounds-1783714830440.jpg',
    optimizationTip: 'Anti-Aliasing Very Low, Motion Blur Off, Sharpen On. Проводной интернет обязателен для стабильного пинга.',
  },
  {
    title: 'Stalzone',
    imageUrl: '/images/games/stalzone.jpg',
    optimizationTip: 'Понизьте тени и дистанцию. Очистите PipelineCache при фризах. Выберите сервер с минимальным пингом.',
  },
  {
    title: 'Lies of P',
    imageUrl: '/images/games/lies-of-p-1783714683623.jpg',
    optimizationTip: 'DLSS/FSR Quality, тени Medium. Закройте overlay и фоновые приложения — игра нагружает CPU.',
  },
  {
    title: 'Horizon Zero Dawn',
    imageUrl: '/images/games/horizon-zero-dawn-1783714732778.jpg',
    optimizationTip: 'FSR 2.0 Quality, Motion Blur Off. Обновите драйверы GPU до последней версии.',
  },
  {
    title: 'Valorant',
    imageUrl: '/images/games/valorant-1783714778748.jpg',
    optimizationTip: 'Все Low, Multithreaded Rendering On. NVIDIA Reflex On+Boost. Закройте Riot Client overlay при проблемах.',
  },
  {
    title: 'Apex Legends',
    imageUrl: '/images/games/apex-legends-1783714861323.webp',
    optimizationTip: 'Texture Streaming Budget минимум, Impact Marks Off. Launch: -novid -high +fps_max 0.',
  },
];
